MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
DATASETS:
  TRAIN: ("coco_format_train",)
  TEST: ("coco_format_val",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (12, 16)
  MAX_ITER: 18
  IMS_PER_BATCH: 1

INPUT:
  MIN_SIZE_TRAIN: 400
  MIN_SIZE_TEST: 400

TEST:
  IMS_PER_BATCH: 1
